### ISSUE TITLE
Marino says Adafruit GPS code not working???

### ISSUE THREAD

**Issue by devangel77b** [usna-sailbot/nav-2020#1]

**Comment by Lukemarino** [comment]
Demonstration Code for 11/15's bench test has been placed in the Luke-dev branch

**Comment by devangel77b** [comment]
On Adafruit Absolute GPS, it looks like the mbed library being used has not been updated since 2014, but the official Adafruit (arduino) library has changes as recent as 13 days ago. Probably need to copy the official Adafruit library instead of mlee350's mbed code to be sure this will work...

**Comment by devangel77b** [comment]
For example, the most recent official Adafruit version of parsehex() has a return 0; at the end of the cases so it always returns a value.

Also the official Adafruit version of sendCommand has calling signature
void Adafruit_GPS::sendCommand(const char *str)
which would allow sending of constant string literals.

**Comment by devangel77b** [comment]
Proposed fix: Evangelista port the newer Adafruit library.

**Comment by devangel77b** [comment]
I tried porting the newer ADafruit library as https://github.com/usna-sailbot/mbed_Adafruit_GPS library. I'm not sure I did it all right and didn't even try to do the I2C stuff, but it compiles without errors?

**Comment by Lukemarino** [comment]
fixed
