### ISSUE TITLE
Missing member function?

### ISSUE THREAD

**Issue by Lukemarino** [usna-sailbot/nav-2020#2]
https://github.com/usna-sailbot/nav-2020/blob/cf46b00f0818ca984fb9616f95d9756406ec1ccd/main.cpp#L125

The compiler claims there is not .read function in the SailbotGPS library. Am I referencing it wrong since the Adafruit library is nested inside of the SailbotGPS library?

**Comment by devangel77b** [comment]
mbed_Adafruit_GPS works differently from the previous Sparkfun GPS. The intent with SailbotGPS was to abstract that away but SailbotGPS has not been updated. For now use mbed_Adafruit_GPS library as shown in the parsing test main.cpp file I sent. We should discuss how you want the GPS interface to work... most probably it should expose things like lat lon time etc.

**Comment by Lukemarino** [comment]
Works now
